language: python
sudo: false
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
env:
  - DJANGO="Django>=1.7,<1.8"
  - DJANGO="Django>=1.8,<1.9"
  - DJANGO="Django>=1.9,<1.10"
matrix:  # see https://docs.djangoproject.com/en/dev/faq/install/
  exclude:
    - python: "3.5"
      env: DJANGO="Django>=1.7,<1.8"
  exclude:
    - python: "3.2"
      env: DJANGO="Django>=1.9,<1.10"
  exclude:
    - python: "3.3"
      env: DJANGO="Django>=1.9,<1.10"
# command to install dependencies
install:
  - pip install $DJANGO
  - pip install coveralls
  - python setup.py develop
script: coverage run example/manage.py test -v2
after_success:
  - coveralls
